title: Kaqui Records Docs
description: Architecture and implementation docs for the Nuxt + Contentful + Shopify storefront
remote_theme: pages-themes/primer@v0.6.0 #https://github.com/pages-themes/primer
plugins:
  - jekyll-remote-theme
